# -*- coding: utf-8 -*-
"""Transfer_Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHjJeyTE-M4QRXhetSD8m67e8BFnBZnh

#### Task 1: Dataset Preparation
"""

# Import dependencies
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import torchvision.models as models
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader, random_split

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Transform for visualization (raw 32x32 images, pixel values in [0,1])
display_transform = transforms.ToTensor()

# Transform for the model (resized to 224x224 for VGG16, pixel values in [0,1])
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

# Load Train dataset
train_dataset = torchvision.datasets.CIFAR10(
    root='./data',
    download=True,
    train=True,
    transform=train_transform
)

# Dataset used only for displaying raw sample images
display_dataset = torchvision.datasets.CIFAR10(
    root='./data',
    download=True,
    train=True,
    transform=display_transform
)

# Load Test dataset
test_dataset = torchvision.datasets.CIFAR10(
    root='./data',
    download=True,
    train=False,
    transform=test_transform
)

# Validation Split
train_size = 45000
validation_size = 5000

train_subset, validation_subset = random_split(
    train_dataset,
    [train_size, validation_size]
)

# Print Dataset Dimensions
print("Training Dataset :", len(train_dataset))
print("Testing Dataset  :", len(test_dataset))

image, label = display_dataset[0]
print("Image Shape :", image.shape)
print("Label       :", label)

# Display first 10 sample images
classes = display_dataset.classes

plt.figure(figsize=(15, 4))

for i in range(10):
    image, label = display_dataset[i]
    plt.subplot(2, 5, i + 1)
    image = image.permute(1, 2, 0)
    plt.imshow(image)
    plt.title(classes[label])
    plt.axis("off")

plt.suptitle("Sample CIFAR-10 Images")
plt.tight_layout()
plt.show()

"""**Inference:** The CIFAR-10 dataset consists of 60,000 32x32 colour images spread across 10 balanced classes, with 50,000 used for training and 10,000 for testing.

#### Task 2: Transfer Learning - Model Setup (VGG16)
"""

# Load VGG16 pretrained on ImageNet
vgg16 = models.vgg16(weights=models.VGG16_Weights.IMAGENET1K_V1)
print(vgg16)

# Remove the original classifier and freeze the convolutional base
class TransferCNN(nn.Module):

    def __init__(self, base_model, num_classes=10):
        super().__init__()

        # Convolutional base (feature extractor) of the pretrained model
        self.features = base_model.features

        # Freeze all convolutional layers
        for param in self.features.parameters():
            param.requires_grad = False

        # Global Average Pooling layer
        self.gap = nn.AdaptiveAvgPool2d(1)

        # New classifier head
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(256, num_classes)   # Softmax applied via CrossEntropyLoss
        )

    def forward(self, x):
        x = self.features(x)
        x = self.gap(x)
        x = self.classifier(x)
        return x

# Create the model
model = TransferCNN(vgg16, num_classes=10).to(device)
print(model)

# Count trainable vs total parameters
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print("Total Parameters     :", total_params)
print("Trainable Parameters :", trainable_params)

"""#### Task 3: Model Training"""

# Create Data Loaders
batch_size = 32

train_loader = DataLoader(train_subset, batch_size=batch_size, shuffle=True, num_workers=2)
validation_loader = DataLoader(validation_subset, batch_size=batch_size, shuffle=False, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

# Loss Function and Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=0.001
)

# Training loop
def train_model(model, optimizer, epochs):

    train_loss_history = []
    train_accuracy_history = []
    validation_loss_history = []
    validation_accuracy_history = []

    for epoch in range(epochs):

        # =========================
        # TRAINING
        # =========================
        model.train()

        running_loss = 0.0
        correct = 0
        total = 0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * images.size(0)
            _, predicted = torch.max(outputs, 1)
            correct += (predicted == labels).sum().item()
            total += labels.size(0)

        train_loss = running_loss / total
        train_accuracy = 100 * correct / total

        # =========================
        # VALIDATION
        # =========================
        model.eval()

        val_running_loss = 0.0
        val_correct = 0
        val_total = 0

        with torch.no_grad():
            for images, labels in validation_loader:
                images, labels = images.to(device), labels.to(device)

                outputs = model(images)
                loss = criterion(outputs, labels)

                val_running_loss += loss.item() * images.size(0)
                _, predicted = torch.max(outputs, 1)
                val_correct += (predicted == labels).sum().item()
                val_total += labels.size(0)

        validation_loss = val_running_loss / val_total
        validation_accuracy = 100 * val_correct / val_total

        train_loss_history.append(train_loss)
        train_accuracy_history.append(train_accuracy)
        validation_loss_history.append(validation_loss)
        validation_accuracy_history.append(validation_accuracy)

        print(f"Epoch [{epoch+1}/{epochs}] "
              f"Train Loss: {train_loss:.4f} Train Acc: {train_accuracy:.2f}% "
              f"Val Loss: {validation_loss:.4f} Val Acc: {validation_accuracy:.2f}%")

    return train_loss_history, train_accuracy_history, validation_loss_history, validation_accuracy_history

# Train the model (frozen convolutional base)
epochs = 10

(train_loss_history, train_accuracy_history,
 validation_loss_history, validation_accuracy_history) = train_model(model, optimizer, epochs)

# Accuracy before fine tuning
accuracy_before_finetune = validation_accuracy_history[-1]
print(f"Validation Accuracy Before Fine Tuning: {accuracy_before_finetune:.2f}%")

"""#### Task 4: Fine Tuning"""

# Unfreeze the last convolutional block of VGG16
# VGG16 features: last block is layers 24 to 30 (5th conv block + pooling)
for name, param in model.features.named_parameters():
    layer_index = int(name.split('.')[0])
    if layer_index >= 24:
        param.requires_grad = True

trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Trainable Parameters After Unfreezing:", trainable_params)

# Re-create optimizer with a lower learning rate for fine tuning
finetune_optimizer = torch.optim.Adam(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=0.0001
)

finetune_epochs = 5

(ft_train_loss_history, ft_train_accuracy_history,
 ft_validation_loss_history, ft_validation_accuracy_history) = train_model(
    model, finetune_optimizer, finetune_epochs
)

# Combine training history from both phases
train_loss_history += ft_train_loss_history
train_accuracy_history += ft_train_accuracy_history
validation_loss_history += ft_validation_loss_history
validation_accuracy_history += ft_validation_accuracy_history

accuracy_after_finetune = validation_accuracy_history[-1]

print(f"Validation Accuracy Before Fine Tuning : {accuracy_before_finetune:.2f}%")
print(f"Validation Accuracy After Fine Tuning  : {accuracy_after_finetune:.2f}%")

"""#### Task 5: Model Evaluation"""

# Import evaluation metrics
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Testing loop
model.eval()

all_predictions = []
all_labels = []

correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        all_predictions.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Accuracy
test_accuracy = 100 * correct / total

# Precision
precision = precision_score(all_labels, all_predictions, average="weighted")

# Recall
recall = recall_score(all_labels, all_predictions, average="weighted")

# F1 Score
f1 = f1_score(all_labels, all_predictions, average="weighted")

print(f"Testing Accuracy : {test_accuracy:.2f}%")
print(f"Precision        : {precision:.4f}")
print(f"Recall           : {recall:.4f}")
print(f"F1 Score         : {f1:.4f}")

# Confusion Matrix
cm = confusion_matrix(all_labels, all_predictions)

plt.figure(figsize=(8, 6))
plt.imshow(cm)
plt.title("Confusion Matrix - VGG16 Transfer Learning")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.colorbar()
plt.xticks(range(10), classes, rotation=45)
plt.yticks(range(10), classes)
plt.tight_layout()
plt.show()

# Classification Report
print(classification_report(all_labels, all_predictions, target_names=classes))

"""**Inference:** The confusion matrix and classification report highlight which classes are frequently confused (e.g. visually similar classes such as cat/dog or automobile/truck), helping identify where the model needs improvement.

#### Mandatory Plots
"""

# Training Accuracy vs Validation Accuracy
plt.figure(figsize=(8, 5))
plt.plot(train_accuracy_history, label="Training")
plt.plot(validation_accuracy_history, label="Validation")
plt.axvline(x=epochs - 1, color='red', linestyle='--', label='Fine Tuning Starts')
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.title("Training vs Validation Accuracy")
plt.legend()
plt.grid(True)
plt.show()

# Training Loss vs Validation Loss
plt.figure(figsize=(8, 5))
plt.plot(train_loss_history, label="Training")
plt.plot(validation_loss_history, label="Validation")
plt.axvline(x=epochs - 1, color='red', linestyle='--', label='Fine Tuning Starts')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

"""**Inference:** Both training and validation curves should show accuracy increasing and loss decreasing over epochs, with a further shift visible after fine tuning begins."""

# Misclassified Images (Optional)
all_predictions = np.array(all_predictions)
all_labels = np.array(all_labels)

misclassified_indices = np.where(all_predictions != all_labels)[0][:10]

plt.figure(figsize=(15, 4))

for i, idx in enumerate(misclassified_indices):
    image, true_label = test_dataset[idx]
    image = image.permute(1, 2, 0)

    plt.subplot(2, 5, i + 1)
    plt.imshow(image)
    plt.title(f"True: {classes[true_label]}\nPred: {classes[all_predictions[idx]]}")
    plt.axis("off")

plt.suptitle("Sample Misclassified Images")
plt.tight_layout()
plt.show()

"""**Inference:** Misclassified images often share visual similarities with the predicted class, such as similar colours, shapes, or backgrounds, which explains the model's confusion."""