# -*- coding: utf-8 -*-
"""notebook0c0a62a4d0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sj8oeOT-pvyiChPWvBxxQlBTAyhvvfrJ

### Task 1: Dataset Exploration
"""

# Import libraries
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

# Load Fashion-MNIST dataset
(X_train, Y_train), (X_test, Y_test) = keras.datasets.fashion_mnist.load_data()

# Dataset Dimensions
print("X_train dimensions: ", X_train.shape)
print("Y_train dimensions: ", Y_train.shape)
print("X_test dimensions: ", X_test.shape)
print("Y_test dimensions: ", Y_test.shape)

# Class names
class_names = [
    "T-shirt/Top", "Trouser", "Pullover", "Dress", "Coat",
    "Sandal", "Shirt", "Sneaker", "Bag", "Ankle Boot"
]

# Display 10 images

plt.figure(figsize=(12,5))

for i in range(10):
  plt.subplot(2, 5, i+1)
  plt.imshow(X_train[i], cmap = 'grey')
  plt.title(class_names[Y_train[i]])
  plt.axis("off")

plt.tight_layout()
plt.savefig(fname = "sample_images.eps", dpi = 600, format = "eps")
plt.show()

# Plot class distributions

unique, counts = np.unique(Y_train, return_counts = True)

plt.figure(figsize = (8, 5))
plt.bar(class_names, counts)
plt.title("Fashion-MNIST Class Distribution")
plt.xticks(rotation=45)
plt.xlabel("Class")
plt.ylabel("Number of Images")

plt.tight_layout()
plt.savefig(fname = "class_distribution.eps", dpi = 600, format = "eps")
plt.show()

"""### Task 2: Data Preprocessing"""

# Shape before preprocessing
print("X_train Shape: ", X_train.shape)
print("X_test Shape: ", X_test.shape)

# Flattening
X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1)

# Normalizing
X_train = X_train.astype("float32")/255.0
X_test = X_test.astype("float32")/255.0

# Shape after preprocessing
print("X_train Shape: ", X_train.shape)
print("X_test Shape: ", X_test.shape)

# Verify normalization
print("Minimum pixel value:", X_train.min())
print("Maximum pixel value:", X_train.max())

"""### Task 3: Model Construction"""

model = keras.Sequential([
    keras.layers.Input(shape = (784,)),
    keras.layers.Dense(128, activation = "relu"),
    keras.layers.Dense(64, activation = "relu"),
    keras.layers.Dense(10, activation = "softmax")
])

model.summary()

"""### Task 4: Model Training"""

from tensorflow.keras.utils import to_categorical

# Convert integer labels to one-hot vectors
y_train = to_categorical(Y_train, num_classes=10)
y_test = to_categorical(Y_test, num_classes=10)

# Compile the model
model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2
)

"""#### Training Accuracy vs Epoch"""

plt.figure(figsize=(8,5))
plt.plot(history.history["accuracy"], marker="o")
plt.title("Training Accuracy vs Epoch")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.grid(True)
plt.show()

"""#### Validation Accuracy vs Epoch"""

plt.figure(figsize=(8,5))
plt.plot(history.history["val_accuracy"], marker="o")
plt.title("Validation Accuracy vs Epoch")
plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.grid(True)
plt.show()

"""#### Training Loss vs Epoch"""

plt.figure(figsize=(8,5))
plt.plot(history.history["loss"], marker="o")
plt.title("Training Loss vs Epoch")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.grid(True)
plt.show()

"""#### Validation Loss vs Epoch


"""

plt.figure(figsize=(8,5))
plt.plot(history.history["val_loss"], marker="o")
plt.title("Validation Loss vs Epoch")
plt.xlabel("Epoch")
plt.ylabel("Validation Loss")
plt.grid(True)
plt.show()

"""### Task 5: Model Evaluation"""

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Predict probabilities
y_pred_prob = model.predict(X_test)

# Convert probabilities to predicted class labels
y_pred = np.argmax(y_pred_prob, axis=1)

# Convert one-hot encoded labels back to integer labels
y_true = np.argmax(y_test, axis=1)

# Compute evaluation metrics
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average="weighted")
recall = recall_score(y_true, y_pred, average="weighted")
f1 = f1_score(y_true, y_pred, average="weighted")

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)

# Classification report
report = classification_report(y_true, y_pred)

# Print results
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-Score : {f1:.4f}")

print("\nConfusion Matrix")
print(cm)

print("\nClassification Report")
print(report)

"""#### Confusion Matrix"""

plt.figure(figsize=(8,6))
plt.imshow(cm, cmap="Blues")
plt.colorbar()
plt.xticks(range(10), class_names, rotation=45)
plt.yticks(range(10), class_names)
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i,j],
                 ha="center",
                 va="center",
                 fontsize=8)

plt.tight_layout()
plt.show()

"""### Hyperparameter Optimization"""

# Install compatible SciKeras and Scikit-learn
!pip uninstall -y scikit-learn scikeras
!pip install -q "scikit-learn==1.5.2" "scikeras==0.13.0"

import sklearn, scikeras
print("scikit-learn:", sklearn.__version__)
print("scikeras:", scikeras.__version__)

import numpy as np
import tensorflow as tf
from tensorflow import keras

from scikeras.wrappers import KerasClassifier

from sklearn.model_selection import RandomizedSearchCV

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Reload integer labels (because earlier we converted them into one-hot)

(_, y_train_int), (_, y_test_int) = keras.datasets.fashion_mnist.load_data()

# Build configurable model

def create_model(
    hidden_layers=2,
    hidden_neurons=128,
    learning_rate=0.001,
    optimizer="adam",
    activation="relu",
    dropout_rate=0.0,
):

    model = keras.Sequential()
    model.add(keras.layers.Input(shape=(784,)))

    for i in range(hidden_layers):
        model.add(
            keras.layers.Dense(
                hidden_neurons,
                activation=activation
            )
        )

        if dropout_rate > 0:
            model.add(
                keras.layers.Dropout(dropout_rate)
            )

    model.add(
        keras.layers.Dense(
            10,
            activation="softmax"
        )
    )

    # Optimizer Selection

    if optimizer == "adam":
        opt = keras.optimizers.Adam(
            learning_rate=learning_rate
        )

    elif optimizer == "sgd":
        opt = keras.optimizers.SGD(
            learning_rate=learning_rate
        )

    else:
        opt = keras.optimizers.RMSprop(
            learning_rate=learning_rate
        )

    model.compile(
        optimizer=opt,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

# Wrap model using SciKeras

classifier = KerasClassifier(
    model=create_model,
)

# Hyperparameter Search Space

param_grid = {
    "model__hidden_layers": [1, 2, 3],
    "model__hidden_neurons": [32, 64, 128, 256],
    "model__learning_rate": [0.1, 0.01, 0.001],
    "model__optimizer": ["sgd", "adam", "rmsprop"],
    "model__activation": ["relu", "tanh", "sigmoid"],
    "model__dropout_rate": [0.0, 0.2, 0.5],
    "batch_size": [16, 32, 64, 128],
    "epochs": [10, 20, 30]
}

# Randomized Search
random_search = RandomizedSearchCV(
    estimator=classifier,
    param_distributions=param_grid,
    n_iter=30,
    cv=3,               # 3-fold instead of 5, to cut compute further
    scoring="accuracy",
    verbose=2,
    n_jobs=-1,
    random_state=42
)

# Start Search

print("Starting Hyperparameter Search...\n")

random_search.fit(
    X_train.astype(np.float32),
    y_train_int.astype(np.float32)
)

print("\nHyperparameter Search Completed!")

# Best Parameters

print("\nBest Hyperparameters:\n")
print(random_search.best_params_)

print("\nBest Cross Validation Accuracy:")
print(random_search.best_score_)

# Best Model
best_model = random_search.best_estimator_

# Prediction
y_pred = best_model.predict(X_test)

# Evaluation

accuracy = accuracy_score(y_test_int, y_pred)
precision = precision_score(y_test_int, y_pred, average="weighted")
recall = recall_score(y_test_int, y_pred, average="weighted")
f1 = f1_score(y_test_int, y_pred, average="weighted")
cm = confusion_matrix(y_test_int, y_pred)
report = classification_report(y_test_int, y_pred)

# Print Results

print("\n===============================")
print("Optimized Model Performance")
print("===============================\n")

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")
print("\nConfusion Matrix\n")
print(cm)
print("\nClassification Report\n")
print(report)

# Compare with Baseline

baseline_loss, baseline_accuracy = model.evaluate(X_test, y_test, verbose=0)

print("\n===============================")
print("Comparison")
print("===============================\n")

print(f"Baseline Accuracy  : {baseline_accuracy:.4f}")
print(f"Optimized Accuracy : {accuracy:.4f}")

"""#### Hyperparameter Search Result"""

results = random_search.cv_results_
plt.figure(figsize=(8,5))
plt.plot(results["mean_test_score"], marker="o")
plt.xlabel("Random Search Iteration")
plt.ylabel("Mean CV Accuracy")
plt.title("Hyperparameter Search Results")
plt.grid(True)
plt.show()

"""#### Baseline vs Optimized Accuracy"""

plt.figure(figsize=(6,5))

plt.bar(
    ["Baseline","Optimized"],
    [baseline_accuracy, accuracy]
)

plt.ylabel("Accuracy")
plt.title("Baseline vs Optimized Model")
plt.ylim(0,1)
plt.show()