# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7iCd7UNw2YAWrhc2QqRsVBNymiIqBzX

#### Task 1: Load CIFAR 10
"""

# Import dependencies
import torch
import torchvision
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
from torch.utils.data import random_split

# Load Image Transform
transform = transforms.ToTensor()

# Load Train dataset
train_dataset = torchvision.datasets.CIFAR10(
    root = './data',
    download = True,
    train = True,
    transform = transform
)

# Validation Dataset
train_size = 45000
validation_size = 5000

train_subset, validation_subset = random_split(
    train_dataset,
    [train_size, validation_size]
)

# Load Test dataset
test_dataset = torchvision.datasets.CIFAR10(
    root = './data',
    download = True,
    train = False,
    transform = transform
)

# Print Dataset Dimensions
print("Training Datset: ", len(train_dataset))
print("Test Datset: ", len(test_dataset))

image, label = train_dataset[0]

print("Image Shape :", image.shape)
print("Label :", label)

# Display first 10 images
classes = train_dataset.classes

plt.figure(figsize = (15,4))

for i in range(10):
  image, label = train_dataset[i]

  plt.subplot(2, 5, i + 1)

  image = image.permute(1, 2, 0)

  plt.imshow(image)
  plt.title(classes[label])
  plt.axis("off")

plt.tight_layout()
plt.show()

# Plot Class Distribution
labels = [label for _,label in train_dataset]

count = Counter(labels)

classes = train_dataset.classes

plt.figure(figsize = (10, 5))
plt.bar(classes, [count[i] for i in range(len(classes))])
plt.title("Class Distribution of CIFAR-10")
plt.xlabel("Classes")
plt.ylabel("Number of Images")
plt.xticks(rotation=45)
plt.show()

"""#### Task 2: Implement Convolutional Layer"""

import torch.nn as nn

# Take a Sample Image
image, label = train_dataset[0]
image = image.unsqueeze(0)

# Creating the Convolutional Layers

conv3 = nn.Conv2d(
    in_channels = 3,
    out_channels = 1,
    kernel_size = 3,
    stride = 1,
    padding = 0
)

conv5 = nn.Conv2d(
    in_channels = 3,
    out_channels = 1,
    kernel_size = 5,
    stride = 1,
    padding = 0
)

conv7 = nn.Conv2d(
    in_channels = 3,
    out_channels = 1,
    kernel_size = 7,
    stride = 1,
    padding = 0
)

# Perform the Convolution Operation
feature3 = conv3(image)
feature5 = conv5(image)
feature7 = conv7(image)

# Print the Resultant Dimensions
print("Input Image Shape: ", image.shape)
print("After 3x3 Filter: ", feature3.shape)
print("After 5x5 Filter: ", feature5.shape)
print("After 7x7 Filter: ", feature7.shape)

"""#### Task 3: Study Hyperparameter"""

# Using the same Sample Image

# Stride = 1
conv = nn.Conv2d(
    in_channels = 3,
    out_channels = 1,
    kernel_size = 3,
    stride = 1,
    padding = 0
)

feature = conv(image)

print("Input Image Shape: ", image.shape)
print("After 3x3 Filter with Stride of 1: ", feature.shape)

# Stride = 2
conv = nn.Conv2d(
    in_channels = 3,
    out_channels = 1,
    kernel_size = 3,
    stride = 2,
    padding = 0
)

feature = conv(image)

print("Input Image Shape: ", image.shape)
print("After 3x3 Filter with Stride of 2: ", feature.shape)

# Padding = 'same'
conv = nn.Conv2d(
    in_channels = 3,
    out_channels = 1,
    kernel_size = 3,
    stride = 1,
    padding = 'same'
)

feature = conv(image)

print("Input Image Shape: ", image.shape)
print("After 3x3 Filter with Padding of 'same': ", feature.shape)

# Stride = 1
conv = nn.Conv2d(
    in_channels = 3,
    out_channels = 1,
    kernel_size = 3,
    stride = 1,
    padding = 'valid'
)

feature = conv(image)

print("Input Image Shape: ", image.shape)
print("After 3x3 Filter with Padding of 'valid': ", feature.shape)

"""#### Task 4: Visualize feature maps after the first convolution layer."""

# Using the same Sample Image

# Creating the Convolutional Layer
conv = nn.Conv2d(
    in_channels=3,
    out_channels=8,
    kernel_size=3
)

# Performing the Convolution Operation
feature_maps = conv(image)

# Printing the Feature Map's Shape
feature_maps = feature_maps.squeeze(0)
print("Feature Map's Shape: ", feature_maps.shape)

# Plot those Feature Maps

plt.figure(figsize = (12, 6))

for i in range(8):
  plt.subplot(2, 4, i+1)
  plt.imshow(feature_maps[i].detach().numpy(), cmap = 'grey')
  plt.title(f'Feature {i+1}')
  plt.axis('off')

plt.tight_layout()
plt.show()

"""#### Task 5: Pooling"""

# Max Pooling
max_pool = nn.MaxPool2d(
    kernel_size = 2,
    stride = 2
)

max_output = max_pool(feature_maps)
print(max_output.shape)

# Avg Pooling
avg_pool = nn.AvgPool2d(
    kernel_size = 2,
    stride = 2
)

avg_output = avg_pool(feature_maps)
print(avg_output.shape)

# Visualizing the difference - max_pool

plt.figure(figsize = (12, 6))

for i in range(8):
  plt.subplot(2, 4, i+1)
  plt.imshow(max_output[i].detach().numpy(), cmap = 'grey')
  plt.title(f'Feature {i+1}')
  plt.axis('off')

plt.tight_layout()
plt.show()

# Visualizing the difference - avg_pool

plt.figure(figsize = (12, 6))

for i in range(8):
  plt.subplot(2, 4, i+1)
  plt.imshow(avg_output[i].detach().numpy(), cmap = 'grey')
  plt.title(f'Feature {i+1}')
  plt.axis('off')

plt.tight_layout()
plt.show()

"""#### Task 6: CNN Implementation and Training"""

# CNN Class

class CNN(nn.Module):

  def __init__(self):

    super().__init__()

    self.features = nn.Sequential(

        nn.Conv2d(
            in_channels = 3,
            out_channels = 8,
            kernel_size = 3,
            padding = 1
        ),

        nn.ReLU(),

        nn.MaxPool2d(
            kernel_size = 2,
            stride = 2
        ),

        nn.Conv2d(
            in_channels = 8,
            out_channels = 16,
            kernel_size = 3,
            padding = 1
        ),

        nn.ReLU(),

        nn.MaxPool2d(
            kernel_size = 2,
            stride = 2
        )

    )

    self.classifier = nn.Sequential(

        nn.Flatten(),

        nn.Linear(
            16*8*8,
            10
        )

    )


  def forward(self, x):
    x = self.features(x)
    x = self.classifier(x)
    return x

# Create the model
model = CNN()
print(model)

# Create Data Loader
from torch.utils.data import DataLoader

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

validation_loader = DataLoader(
    validation_subset,
    batch_size=32,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False
)

# Loss Function
criterion = nn.CrossEntropyLoss()

# Optimizer
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

# Training loop
epochs = 20

train_loss_history = []
train_accuracy_history = []
validation_loss_history = []
validation_accuracy_history = []

for epoch in range(epochs):

    # =========================
    # TRAINING
    # =========================

    model.train()

    running_loss = 0
    correct = 0
    total = 0

    for images, labels in train_loader:

        outputs = model(images)

        loss = criterion(outputs, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

    epoch_train_loss = running_loss / len(train_loader)
    epoch_train_accuracy = 100 * correct / total


    # =========================
    # VALIDATION
    # =========================

    model.eval()

    validation_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in validation_loader:

            outputs = model(images)

            loss = criterion(outputs, labels)

            validation_loss += loss.item()

            _, predicted = torch.max(outputs, 1)

            total += labels.size(0)

            correct += (predicted == labels).sum().item()

    epoch_validation_loss = validation_loss / len(validation_loader)
    epoch_validation_accuracy = 100 * correct / total

    # =========================
    # STORING
    # =========================

    train_loss_history.append(epoch_train_loss)
    train_accuracy_history.append(epoch_train_accuracy)
    validation_loss_history.append(epoch_validation_loss)
    validation_accuracy_history.append(epoch_validation_accuracy)

    # =========================
    # PRINTING
    # =========================
    print(
        f"Epoch [{epoch+1}/{epochs}] "
        f"Train Loss: {epoch_train_loss:.4f} "
        f"Train Acc: {epoch_train_accuracy:.2f}% "
        f"Val Loss: {epoch_validation_loss:.4f} "
        f"Val Acc: {epoch_validation_accuracy:.2f}%"
    )

"""#### Task 7: CNN Evaluation"""

# Import
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Testing loop
model.eval()

all_predictions = []
all_labels = []

correct = 0
total = 0

with torch.no_grad():

    for images, labels in test_loader:

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

        all_predictions.extend(predicted.numpy())

        all_labels.extend(labels.numpy())

# Accuracy
accuracy = 100 * correct / total

# Precision
precision = precision_score(
    all_labels,
    all_predictions,
    average="weighted"
)

# Recall
recall = recall_score(
    all_labels,
    all_predictions,
    average="weighted"
)

# F1 Score
f1 = f1_score(
    all_labels,
    all_predictions,
    average="weighted"
)

# Printing Scores
print(f"Accuracy: {accuracy:.4f}%")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

# Confusion Matrix
cm = confusion_matrix(
    all_labels,
    all_predictions
)

plt.figure(figsize=(8,6))
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.colorbar()
plt.show()

# Classification Report
print(
    classification_report(
        all_labels,
        all_predictions,
        target_names=train_dataset.classes
    )
)

"""#### Visualization"""

# Training Accuracy vs Validation Accuracy

plt.figure(figsize=(8,5))
plt.plot(train_accuracy_history, label="Training")
plt.plot(validation_accuracy_history, label="Validation")
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.title("Training vs Validation Accuracy")
plt.legend()
plt.grid(True)
plt.show()

# Training Loss vs Validation Loss

plt.figure(figsize=(8,5))
plt.plot(train_loss_history, label="Training")
plt.plot(validation_loss_history, label="Validation")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()